extraction:
  implementation: dandelion
export:
  implementation: cidoccrm
  language: turtle
  namespaces:
    entity: http://www.hercules.gouv.qc.ca/instances/entities/
    ontology: http://www.cidoc-crm.org/cidoc-crm/
  