translation:
  implementation: azure
  language:
    text: fr
    extraction: en
extraction:
  implementation: dandelion
coreference:
  implementation: stanford
  stanford:
    start_server: False
    endpoint: "http://localhost:9000"
export:
  implementation: cidoccrm
  language: turtle
  namespaces:
    entity: http://culture.gouv.qc.ca/entity/
    ontology: http://erlangen-crm.org/170309/
  