translation:
  implementation: azure
  language:
    text: fr
    extraction: en
extraction:
  implementation: dandelion
coreference:
  implementation: stanford
  stanford:
    start_server: False
    endpoint: "http://localhost:9000"
export:
  implementation: cidoccrm
  language: turtle
  namespaces:
    entity: http://www.hercules.gouv.qc.ca/instances/entities/
    ontology: http://www.cidoc-crm.org/cidoc-crm/
  